---
title: "Policy or Partisanship: Replicating Results From An Analysis of Quasi-Experimental Evidence From Brexit"
author: "Trisha Prabhu"
date: "4/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries:

library(foreign)
library(tidyverse)
library(ggplot2)
library(arm)
library(stargazer)
library(janitor)
library(ggthemes)
library(dplyr)
library(arm)
library(packrat)

# Read in the various "waves" of data:

BES6 <- read.dta("~/Downloads/BES2015_W6_v3.9.dta")
BES7 <- read.dta("~/Downloads/BES2015_W7_v2.2-1.dta")
BES8 <- read.dta("~/Downloads/BES2015_W8_v2.3.dta")
BES9 <- read.dta("~/Downloads/BES2015_W9_v1.7.dta")
BES11 <- read.dta("~/Downloads/BES2015_W11_v1.5.dta")
BES13 <- read.dta("~/Downloads/BES2017_W13_v1.5.dta")

```

### Let's begin by cleaning the data:
```{r}

# Recode EU integration values:

BES8 <- BES8 %>%
  dplyr::mutate(EUIntegrationCon = case_when(EUIntegrationCon == "Unite fully with the European Union" ~ 0,
                                      EUIntegrationCon == "1" ~ 1, EUIntegrationCon == "2" ~ 2,
                                      EUIntegrationCon == "3" ~ 3, EUIntegrationCon == "4" ~ 4,
                                      EUIntegrationCon == "5" ~ 5, EUIntegrationCon == "6" ~ 6,
                                      EUIntegrationCon == "7" ~ 7, EUIntegrationCon == "8" ~ 8,
                                      EUIntegrationCon == "9" ~ 9, EUIntegrationCon == "Protect our independence" ~ 10))
BES8 <- BES8 %>%
  dplyr::mutate(EUIntegrationLab = case_when(EUIntegrationLab == "Unite fully with the European Union" ~ 0,
                                      EUIntegrationLab == "1" ~ 1, 
                                      EUIntegrationLab == "2" ~ 2,
                                      EUIntegrationLab == "3" ~ 3,
                                      EUIntegrationLab == "4" ~ 4,
                                      EUIntegrationLab == "5" ~ 5,
                                      EUIntegrationLab == "6" ~ 6,
                                      EUIntegrationLab == "7" ~ 7,
                                      EUIntegrationLab == "8" ~ 8,
                                      EUIntegrationLab == "9" ~ 9,
                                      EUIntegrationLab == "Protect our independence" ~ 10))

BES8 <- BES8 %>%
  dplyr::mutate(EUIntegrationSelf = case_when(EUIntegrationSelf == "Unite fully with the European Union" ~ 0,
                                       EUIntegrationSelf == "1" ~ 1, 
                                       EUIntegrationSelf == "2" ~ 2,
                                       EUIntegrationSelf == "3" ~ 3,
                                       EUIntegrationSelf == "4" ~ 4,
                                       EUIntegrationSelf == "5" ~ 5,
                                       EUIntegrationSelf == "6" ~ 6,
                                       EUIntegrationSelf == "7" ~ 7,
                                       EUIntegrationSelf == "8" ~ 8,
                                       EUIntegrationSelf == "9" ~ 9,
                                       EUIntegrationSelf == "Protect our independence" ~ 10))

BES9 <- BES9 %>%
  mutate(EUIntegrationCon = case_when(EUIntegrationCon == "Unite fully with the European Union" ~ 0,
                                      EUIntegrationCon == "1" ~ 1, EUIntegrationCon == "2" ~ 2,
                                      EUIntegrationCon == "3" ~ 3, EUIntegrationCon == "4" ~ 4,
                                      EUIntegrationCon == "5" ~ 5, EUIntegrationCon == "6" ~ 6,
                                      EUIntegrationCon == "7" ~ 7, EUIntegrationCon == "8" ~ 8,
                                      EUIntegrationCon == "9" ~ 9, EUIntegrationCon == "Protect our independence" ~ 10))

BES9 <- BES9 %>%
  mutate(EUIntegrationLab = case_when(EUIntegrationLab == "Unite fully with the European Union" ~ 0,
                                      EUIntegrationLab == "1" ~ 1, EUIntegrationLab == "2" ~ 2,
                                      EUIntegrationLab == "3" ~ 3, EUIntegrationLab == "4" ~ 4,
                                      EUIntegrationLab == "5" ~ 5, EUIntegrationLab == "6" ~ 6,
                                      EUIntegrationLab == "7" ~ 7, EUIntegrationLab == "8" ~ 8,
                                      EUIntegrationLab == "9" ~ 9, EUIntegrationLab == "Protect our independence" ~ 10))


BES9 <- BES9 %>%
  mutate(EUIntegrationSelf = case_when(EUIntegrationSelf == "Unite fully with the European Union" ~ 0,
                                       EUIntegrationSelf == "1" ~ 1, EUIntegrationSelf == "2" ~ 2,
                                       EUIntegrationSelf == "3" ~ 3, EUIntegrationSelf == "4" ~ 4,
                                       EUIntegrationSelf == "5" ~ 5, EUIntegrationSelf == "6" ~ 6,
                                       EUIntegrationSelf == "7" ~ 7, EUIntegrationSelf == "8" ~ 8,
                                       EUIntegrationSelf == "9" ~ 9, EUIntegrationSelf == "Protect our independence" ~ 10))

```


### Let's now do some analyses and replication of figures:
```{r}

# Let's analyze the strength of our assumption that there was a sudden change
# in Conservative party positioning, unaffected by other important omitted 
# variables (e.g. a similar change in Labor party positioning).

# Examine perceived Euroskepticism of Conservatives and Labour in Waves 8 and 9
# We're looking at a 0 - 10 scale, with 10 being most Euroskeptic
# Note that Wave 8 is immediately leading up to the referendum; Wave 9 is
# immediately after

con_before <- mean(BES8$EUIntegrationCon, na.rm=TRUE)
con_after <- mean(BES9$EUIntegrationCon, na.rm=TRUE)
lab_before <- mean(BES8$EUIntegrationLab, na.rm=TRUE)
lab_after <-mean(BES9$EUIntegrationLab, na.rm=TRUE)

#  Percentage change in Conservative party positioning:

(con_after - con_before)/con_before

# From the paper: "Only the conservatives exhibited a sudden change in
# positioning on Brexit"; here, we see the average perceived Euroskepticism
# of the Conservatives increase by 8%.

```

### Let's create Table 1:
```{r}

# And now, for some other relevant cleaning:

# Create race variable:

BES8$white <- ifelse(BES8$profile_ethnicity == "White British" | BES8$profile_ethnicity == "Any other white background", 1, 0)

BES8$EUIntegrationCon8 <- BES8$EUIntegrationCon
BES8$partyId8 <- BES8$partyId
BES8$EUIntegrationSelf8 <- BES8$EUIntegrationSelf 

# Create Conservative partyID, for both Waves 8 and 9:

BES8$Con <- ifelse(BES8$partyId =="Conservative", 1, 0)
BES8$Con8 <- BES8$Con 

BES9$Con <- ifelse(BES9$partyId=="Conservative", 1, 0)
BES9$Con9 <- BES9$Con 

BES9$EUIntegrationCon9 <- BES9$EUIntegrationCon
BES9$EUIntegrationSelf9 <- BES9$EUIntegrationSelf 
BES9$partyId9 <- BES9$partyId

# Let's now answer the main question of the paper: do voters switch their party identification as a
# function of their Euroskepticism?

# Let's subset Wave 8 to Conservatives:

BES8subcons <- BES8[BES8$partyId == "Conservative",]

# Let's merge the Conservatives in Wave 8 to the BE9 (post-referendum) data,
# so we can look at switching:

merged <- merge(BES8subcons, BES9, by= "id")

# And here we go! Table 1:

# Let's create a variable that indicates switching:

merged$partyswitcher <- ifelse(merged$partyId8 != merged$partyId9, 1, 0)

# Table 1:
# Note that the independent variable here is the respondent's self-reported level
# of Euroskepticism, on a 0 - 10 scale:

table1reg <- lm(partyswitcher ~ EUIntegrationSelf8, data = merged)
summary(table1reg)

# Let's create a variable that represents the change (post-referendum) in 
# perceived Euroskepticism of Conservatives:

merged$Conchange <- merged$EUIntegrationCon9 - merged$EUIntegrationCon8

# And include it in our regression as an interaction:

intreg1 <- lm(partyswitcher ~ EUIntegrationSelf8 * Conchange, 
              data = merged)
summary(intreg1)

# From the paper (Page 11): the interaction is negative and significant: less 
# Euroskeptic Conservatives who perceive that the party has become increasingly 
# Euroskeptic are especially likely to reject it.

# And now, let's throw everything in: 

merged$country.x <- as.factor(merged$country.x)

intreg1a <- lm(partyswitcher ~ EUIntegrationSelf8 * Conchange + age.x + gender.x 
               + white + country.x, data = merged)
summary(intreg1a)
```

```{r, results = 'asis'}

# And now, let's create our table:

stargazer(table1reg, intreg1, intreg1a, 
          title = "Euroskepticism and Defection from the Conservatives",
          covariate.labels = c("Pre-Referendum Euroskepticism", 
                               "Perceived Change in Conservative Euroskepticism", 
                               "Age",
                               "Female",
                               "White",
                               "Scotland",
                               "Wales", 
                               "Pre-Referendum Euroskepticism:Perceived Change in Conservative Euroskepticism", 
                               "Constant"),
          
# How to get the caption in italics (why isn't "em" working)?
          
          dep.var.caption  = "<em> Dependent variable: </em>",
          dep.var.labels   = "Defect from Conservatives",
          no.space = TRUE, star.cutoffs = c(0.05, 0.01, 0.001),
          font.size = "tiny",
          header = FALSE) 

```

```{r}

# From the paper (Page 11): "of those who identified as Conservative before the 
# referendum, 9.0 percent of respondents with pre-referendum Euroskepticism 
# scores of 4-5 (on a ten-point scale), 9.8 percent of those with scores of 2-3, 
# and 9.9 percent of those with scores of 0-1 turned their backs on the party. 
# The less Euroskeptic a voter was before the referendum, the more likely they 
# were to disaffiliate from the party in the aftermath of its embrace of 
# Brexit."

merge45 <- merged[merged$EUIntegrationSelf8=="5" | merged$EUIntegrationSelf8=="4",]
merge23 <- merged[merged$EUIntegrationSelf8=="3" | merged$EUIntegrationSelf8=="2",]
merge01 <- merged[merged$EUIntegrationSelf8=="1" | merged$EUIntegrationSelf8=="0",]

mean(merge45$partyswitcher,na.rm=TRUE)
mean(merge23$partyswitcher,na.rm=TRUE)
mean(merge01$partyswitcher,na.rm=TRUE)

```

### Let's create Table 2:
```{r}
# Let's now subset to pre-referendum non-Conservatives:

BES8notcons<- BES8[BES8$partyId != "Conservative",] 

# And now, let's merge that info. with our post-referendum data:

merged2 <- merge(BES8notcons, BES9, by="id")

# Who switches to Conservative post-referendum?

merged2$switchtocons <- ifelse(merged2$partyId9 == "Conservative", 1, 0)

# What's the average?

mean(merged2$switchtocons)

# Let's regress folks' self-reported pre-referendum level of Euroskepticism, on
# a scale from 0 - 10, on those who switch to Conservative post-referendum.

table2reg <- lm(merged2$switchtocons ~ merged2$EUIntegrationSelf8)
summary(table2reg)

# Let's create a variable that represents the change (post-referendum) in 
# perceived Euroskepticism of Conservatives:

merged2$Conchange <- merged2$EUIntegrationCon9 - merged2$EUIntegrationCon8

# And include that variable as an interaction:

intreg2 <- lm(merged2$switchtocons ~ merged2$EUIntegrationSelf8 * merged2$Conchange)
summary(intreg2)

# And now, let's throw everything in again:

intreg2a <- lm(merged2$switchtocons ~ merged2$EUIntegrationSelf8 * merged2$Conchange 
              + merged2$age.x + merged2$gender.x + merged2$white + 
                as.factor(merged2$country.x))
summary(intreg2a)

# From the paper: "A one-point increase in pre-referendum Euroskepticism 
# generates a .7 percent increase in the probability of switching loyalties to 
# the Conservatives. And the interaction term is positive and significant, 
# indicating that Euroskeptic non-Conservatives who perceived an increase in 
# Conservative Euroskepticism following the referendum were especially likely to 
#join the Conservatives."

```

```{r, results = 'asis'}

# And finally, let's create Table 2, with everything:

stargazer(table2reg, intreg2, intreg2a, 
          title = "Euroskepticism and Joining the Conservatives",
          covariate.labels = c("Pre-Referendum Euroskepticism", 
                               "Perceived Change in Conservative Euroskepticism", 
                               "Age",
                               "Female",
                               "White",
                               "Scotland",
                               "Wales", 
                               "Pre-Referendum Euroskepticism:Perceived Change in Conservative Euroskepticism", 
                               "Constant"),

# How to get the caption in italics (why isn't "em" working)?
          
          dep.var.caption  = "<em> Dependent variable: </em>",
          dep.var.labels   = "Joined Conservatives",
          no.space = TRUE, star.cutoffs = c(0.05, 0.01,0.001),
          font.size = "tiny",
          header = FALSE) 

```


```{r}

# Let's look at the percent switched for various groups of Euroskepticism 
# scores:

merge256 <- merged2[merged2$EUIntegrationSelf8 =="5" | merged2$EUIntegrationSelf8 =="6",]
merge278 <- merged2[merged2$EUIntegrationSelf8 =="7" | merged2$EUIntegrationSelf8 =="8",]
merge2910 <- merged2[merged2$EUIntegrationSelf8 =="9" | merged2$EUIntegrationSelf8 =="10",]

mean(merge256$switchtocons,na.rm=TRUE)
mean(merge278$switchtocons,na.rm=TRUE)
mean(merge2910$switchtocons,na.rm=TRUE)

# From the paper: "Of those respondents who did not identify as Conservative 
# before the referendum, 2.8 percent with Euroskepticism scores of 5 or 6, 5.0 
# percent with scores of 7 or 8, and 6.7 percent with scores of 9 or 10 joined 
# the Conservatives. The more Euroskeptic the respondent, the more likely they 
# were to swing behind the Conservatives following the party’s shift in policy
# position.

```

### But do strong partisans (e.g. very committed to Conservative) change their policy preferences?
```{r}
# From the paper: "In Figure 1, we look at whether stronger Conservative 
# partisans were more likely to become Euroskeptic following the sudden, as-if 
# random change in Conservative positioning on Brexit than less staunch 
# supporters of the party."

# A respondent’s change in Euroskepticism between Waves 8 and 9:

merged$Euroskepticismchange <- merged$EUIntegrationSelf9 - merged$EUIntegrationSelf8

# Let's subset voters; we can run the same regression on each group:

mergestrong <- merged[merged$partyIdStrength.x=="Very strong",]
mergenotstrong <- merged[merged$partyIdStrength.x!="Very strong",]
   
# Let's create Table 3 (independent variable -- perceived increase in 
# Conservative Euroskepticism):

intreg3B <- lm(Euroskepticismchange ~ Conchange + gender.x + age.x + white 
               + country.x, data = mergestrong)
summary(intreg3B) 

intreg3A <- lm(Euroskepticismchange ~ Conchange + gender.x + age.x + white 
               + country.x, data = mergenotstrong)
summary(intreg3A)

```

```{r, results = 'asis'}

# And finally, our table:

stargazer(intreg3A, intreg3B, 
          title = "Individual Shifts in Euroskepticism",
          no.space = TRUE,
          covariate.labels = c("Perceived Change in Conservative Euroskepticism", 
                               "Female",
                               "Age",
                               "White",
                               "Scotland",
                               "Wales", 
                               "Constant"),
          dep.var.caption  = "Dependent variable:",
          dep.var.labels   = "Change in Personal Euroskepticism:",
          column.labels   = c("Moderate Conservatives", 
                              "Very Strong Conservatives"),
          model.numbers = FALSE,
          star.cutoffs = c(0.05, 0.01,0.001))

# From the paper: There is a clear, statistically significant, positive 
# relationship between Conservative partisans’ perception of their party’s 
# increasing Euroskepticism and their own Euroskepticism. But the size of the 
# effect is limited: even for very strong Conservatives, a one-unit increase in 
# perceived Conservative Euroskepticism on a ten-point scale yields only a 0.22
# - unit increase in personal Euroskepticism. Unsurprisingly, as the relative 
# sizes of the two coefficients in the top row indicate, the effect is stronger 
# among Conservatives who described their partisan identity as very strong 
# before the referendum.

```

### Let's create Figure 1 (which corresponds with Table 3):
```{r}

# First, let's merge Waves 8 and 9:

bigmerge <- merge(BES8, BES9, by = "id")

# And create relevant values:

bigmerge$Euroskepticismchange <- bigmerge$EUIntegrationSelf9 - bigmerge$EUIntegrationSelf8
bigmerge$Conchange <- bigmerge$EUIntegrationCon9 - bigmerge$EUIntegrationCon8

# And now, let's subset to 3 groups:

bigmerge$Partisan[bigmerge$partyId8 != "Conservative"] <- "Non-Conservative"
bigmerge$Partisan[bigmerge$partyId8 == "Conservative" & bigmerge$partyIdStrength.x != "Very strong"] <- "Moderate Conservative"
bigmerge$Partisan[bigmerge$partyId8 == "Conservative" & bigmerge$partyIdStrength.x == "Very strong"] <- "Very Strong Conservative"

# And create relevant variables representing the 3 groups:

bigmergenon <- bigmerge[bigmerge$Partisan == "Non-Conservative",]
bigmergemod<- bigmerge[bigmerge$Partisan == "Moderate Conservative",]
bigmergever <- bigmerge[bigmerge$Partisan == "Very Strong Conservative",]

# What percentage of each group switched?

mean(bigmergenon$Conchange, na.rm = TRUE)
mean(bigmergemod$Conchange, na.rm = TRUE)
mean(bigmergever$Conchange, na.rm = TRUE)

mean(bigmergenon$Euroskepticismchang, na.rm = TRUE)
mean(bigmergemod$Euroskepticismchang, na.rm = TRUE)
mean(bigmergever$Euroskepticismchang, na.rm = TRUE)

bigmerge$Partisan <- factor(bigmerge$Partisan, levels = c("Non-Conservative", 
                                                          "Moderate Conservative", 
                                                          "Very Strong Conservative"))

# Let's make our ggplot:

g <- ggplot(bigmerge, aes(y = Euroskepticismchange, x = Conchange, color = Partisan)) +
  geom_point(size = 0.1) + 
  stat_smooth(method = "lm",se = TRUE) +
  theme_bw() +
  xlab("Perceived Change in Conservative Euroskepticism") +
  ylab("Change in Personal Euroskepticism") 

g

# From the paper: "The intensity of Conservative partisanship determined the 
# extent to which voters followed the party’s evolving position on the EU – or, 
# more precisely, their perception of the party’s evolving position."

```

